### ISSUE TITLE
I'm getting an error when I run the sample project.

### ISSUE THREAD

**Issue by gauthamns** [passsy/android-HoloCircularProgressBar#1]
When I run the sample project, I'm getting a Nullpointerexception for this function. progressBarAnimator.setupEndValues();

03-28 18:04:21.718: E/AndroidRuntime(32572): Caused by: java.lang.NullPointerException
03-28 18:04:21.718: E/AndroidRuntime(32572):    at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:513)
03-28 18:04:21.718: E/AndroidRuntime(32572):    at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:392)
03-28 18:04:21.718: E/AndroidRuntime(32572):    at android.animation.ObjectAnimator.setupEndValues(ObjectAnimator.java:452)
03-28 18:04:21.718: E/AndroidRuntime(32572):    at de.passsy.circularprogressbarsample.CircularProgressBarSample.animate(CircularProgressBarSample.java:76)
03-28 18:04:21.718: E/AndroidRuntime(32572):    at de.passsy.circularprogressbarsample.CircularProgressBarSample.onCreate(CircularProgressBarSample.java:60)

**Comment by passsy** [comment]
just tested it for 4.2 only. 

~fixed
