### ISSUE TITLE
Marker color doesn't change with background color

### ISSUE THREAD

**Issue by andreavico** [passsy/android-HoloCircularProgressBar#15]
When background color is changed via setProgressBackgroundColor, the marker color doesn't change, while when the background color is set via XML the marker one changes accordingly.

To fix this, I simply added in function setProgressBackgroundColor

```
updateMarkerColor();
```

(Sorry, I'm new to Git and Github, I've no idea how to setup a branch and send a merge request)

**Comment by passsy** [comment]
Correct. I missed that.

If you are new to git try to create a pull request with this fix. It's a good practice :wink:

**Comment by andreavico** [comment]
Pushed ;)

**Comment by passsy** [comment]
well done!

btw you can reference issues in your commit messages with #<issue id>

**Comment by andreavico** [comment]
Oh, didn't know that, thanks!
