### ISSUE TITLE
When put inside a ScrollView, it disappears

### ISSUE THREAD

**Issue by andreavico** [passsy/android-HoloCircularProgressBar#17]
I've put holoCircularProgressBar inside a ScrollView and it disappeared. After investigating the problem, it resulted it received height=0. And a brief Internet research shows it's caused by faulty managing of measures inside onMeasure.

**Comment by passsy** [comment]
I suggest not to use this ProgressBar as single child of a `ScrollView`. Wrap it in a simple `LinearLayout` does the trick.

Anyway, I fixed the bug: e5e726940a841eef0d17a38dc42c2ff2c05533d9
