### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by sw1ftc0d3r** [passsy/android-HoloCircularProgressBar#18]
Hi, it's possible to drag the progress bar on touch event of marker? 
Thanks!

**Comment by passsy** [comment]
sure, that's easy. Override `onTouchEvent()` calculate the angle and call `setProgress`.

But it's not included in this `View` because this is a ProgressBar and not a SeekBar. But feel free to fork :)

**Comment by sw1ftc0d3r** [comment]
Thanks for the answer!
