### ISSUE TITLE
Can't use XML attuributes like "app:stroke_width="20dp""

### ISSUE THREAD

**Issue by wheam** [passsy/android-HoloCircularProgressBar#19]
if i add the attuributes like "app:stroke_width="20dp"" in a   de.passsy.holocircularprogressbar.HoloCircularProgressBar,
the application will crash because Error Inflating.

**Comment by wheam** [comment]
So is there no one to follow errors ? May I give a pull request ?

**Comment by passsy** [comment]
You forgot to add

```
xmlns:app="http://schemas.android.com/apk/res-auto"
```
