### ISSUE TITLE
Change stroke width from code,

### ISSUE THREAD

**Issue by peterszucs** [passsy/android-HoloCircularProgressBar#24]
Hi,
I'm adding this view to my container layout from code. is it possible to set the stroke width not from xml but from code? , by the way it is a very good stuff you made.
thanks for your answer, 
Peter

**Comment by passsy** [comment]
Thanks for your feedback. Here is the method. But I forgot to make this method public.

```
progressBar.setWheelSize(20);
```

so you need the make `setWheelSize` public and add the update methods. Here is the complete code you need to add:

```
public void setWheelSize(final int dimension) {
    mCircleStrokeWidth = dimension;

    // update the paints
    updateBackgroundColor();
    updateMarkerColor();
    updateProgressColor();
}
```

// not tested

**Comment by peterszucs** [comment]
Thanks for your quick answer. It _works_ , so I can say: tested. Thank you.

**Comment by passsy** [comment]
added to `development` branch
