### ISSUE TITLE
change color of bar in progress and setting different durations

### ISSUE THREAD

**Issue by guyzk** [passsy/android-HoloCircularProgressBar#28]
Hi There,

I am looking for a similar solution in my app but i need to know if a few things are possible.
1) Is it possible to change the color of the progress bar dynamically while in progress? 
2) Can i set the animation completion duration? e.g. draw a full circle in 60 seconds and stop

**Comment by passsy** [comment]
1) yes
2) yes

Pro-Tip: use the `development` branch. There are some fixes for dynamically changes and it will be merged soon into the `master`

**Comment by guyzk** [comment]
Thx. will do
