### ISSUE TITLE
Setting a Duration

### ISSUE THREAD

**Issue by codyjhsieh** [passsy/android-HoloCircularProgressBar#29]
Although some people have asked this question all have eventually figured out how to set a duration (ex. 20000 milliseconds) before a published answer could be posted. How do I animate the holocircularprogressbar much like the countdown timer so that an input would show a smooth animation that lasts the length of the input?

**Comment by passsy** [comment]
Look in the sample Project https://github.com/passsy/android-HoloCircularProgressBar/blob/master/sample/src/de/passsy/circularprogressbarsample/CircularProgressBarSample.java#L183

``` java

    HoloCircularProgressBar progressBar = (HoloCircularProgressBar) findViewById(R.id.holoCircularProgressBar1);
    // animate from 0 to 1
    ObjectAnimator progressBarAnimator = ObjectAnimator.ofFloat(progressBar, "progress", 0, 1);
    // in 20000ms
    progressBarAnimator.setDuration(20000);
    progressBarAnimator.start();
```

**Comment by codyjhsieh** [comment]
However any value above 1000 milliseconds causes stuttering in the animation and does not last the correct duration.

**Comment by passsy** [comment]
I can't reproduce this behavior. It's absolutely smooth. See this app for example: https://play.google.com/store/apps/details?id=personal.andreabasso.clearfocus&hl=de

set the duration to 2 minutes and click start.

There must be another issue in your code
