### ISSUE TITLE
Going from 1.0 progress to 0 or any multiple of 1 does not change the status.

### ISSUE THREAD

**Issue by mikedg1** [passsy/android-HoloCircularProgressBar#3]
Due to line 426,        mProgress = progress % 1.0f;
This makes a progress of 1 save as mProgress = 0, so jumping from progress 1 to 0 fails, although this may be oddity with overdraw that I don't fully understand as well.

**Comment by passsy** [comment]
will be resolved within the next days

**Comment by passsy** [comment]
fixed with commit 3eaa44290845fef148d6583e6db0982eb9da5bed
