### ISSUE TITLE
Switch of thumbs/marker symbol?

### ISSUE THREAD

**Issue by Zordid** [passsy/android-HoloCircularProgressBar#4]
I would love to disable the marker symbol. Apparently that is not possible currently?

**Comment by Zordid** [comment]
Oups. Method found, but even though I call progressBar.setMarkerEnabled(false), I can still see the marker graphics on my circular progress bar. What do I do wrong?

**Comment by Zordid** [comment]
Okay, I am not talking about the marker - you call it the "thumb square". That's what I don't want to see! You should also provide a setThumbEnabled(boolean) method to toggle that!
Thanks!

**Comment by passsy** [comment]
custom markers and no marker will come in the next version

**Comment by Zordid** [comment]
plus custom thumbs and no thumbs, I hope? :)

**Comment by passsy** [comment]
that's what I meant

**Comment by Zordid** [comment]
Could you also make the color changeable during runtime through setProgressColor? I would like to animate the color...

**Comment by passsy** [comment]
I'll try it. see #6

**Comment by Zordid** [comment]
Oups. ;-)

**Comment by passsy** [comment]
you can now disable the thumb with `setThumbEnabled(false)`. see commit bdf27322b10cb4d5cdb59e799281b3e861912a52

custom thumbs aren't supported at the moment
